name: sharkship
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  file_picker: ^10.3.10
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  geolocator: ^14.0.2
  go_router: ^17.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0 # ✅ downgraded from ^4.11.0
  logger: ^2.7.0
  permission_handler: ^12.0.1
  freezed_annotation: ^3.0.0
  equatable: ^2.0.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  riverpod_generator: ^3.0.0
  freezed: ^3.0.0
  freezed_annotation: ^3.0.0
  json_serializable: ^6.6.2 # ✅ downgraded from ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login/
